# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python
      run: |
        python "main.py" $KR_NOTICE $KR_MAJOR_UPDATE $KR_UPDATE $KR_EVENT $LAB_NOTICE $LAB_UPDATE
      env:
        KR_NOTICE: ${{secrets.KR_NOTICE}}
        KR_MAJOR_UPDATE: ${{secrets.KR_MAJOR_UPDATE}}
        KR_UPDATE: ${{secrets.KR_UPDATE}}
        KR_EVENT: ${{secrets.KR_EVENT}}
        LAB_NOTICE: ${{secrets.LAB_NOTICE}}
        LAB_UPDATE: ${{secrets.LAB_UPDATE}}
    - name: Commit
      run: |
        git config --local user.email "hammuu1112@gmail.com"
        git config --local user.name "Action bot"
        git add news
        git commit -m "[Auto] get latest"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: $
        
